const productTypeOptions = [
  { value: "producto_fisico", label: "Producto fisico" },
  { value: "servicio", label: "Servicio" },
];

const packageTypeOptions = [
  { value: "perfil", label: "Perfil" },
  { value: "combo", label: "Combo" },
];

const userRoleOptions = [
  { value: "administrador_maestro", label: "Administrador maestro" },
  { value: "administrador_empresa", label: "Administrador de empresa" },
  { value: "gerente", label: "Gerente" },
  { value: "comprador", label: "Comprador" },
];

const branchStatusOptions = [
  { value: "activa", label: "Activa" },
  { value: "temporalmente_cerrada", label: "Temporalmente cerrada" },
  { value: "inactiva", label: "Inactiva" },
];

const commonImageFields = [
  {
    name: "imagen_url",
    label: "URL externa de imagen",
    type: "url",
    full: true,
    placeholder: "https://...",
  },
  {
    name: "imagen",
    label: "Archivo de imagen",
    type: "file",
    accept: "image/*",
    full: true,
  },
];

const phoneFieldProps = {
  inputMode: "numeric",
  maxLength: 8,
  pattern: "[0-9]{8}",
  phone: true,
  type: "text",
};

export function getResourceConfigs(context) {
  const company = context?.empresa_actual || {};
  const isSuperuser = context?.usuario?.es_superusuario === true;
  const actorRole = context?.perfil?.rol;
  const availableUserRoles = isSuperuser
    ? userRoleOptions
    : actorRole === "administrador_maestro"
      ? userRoleOptions.filter((option) => option.value !== "administrador_maestro")
      : actorRole === "administrador_empresa"
        ? userRoleOptions.filter((option) => ["gerente", "comprador"].includes(option.value))
        : userRoleOptions.filter((option) => option.value === "comprador");

  return {
    familias: {
      key: "familias",
      title: "Familias",
      singular: "familia",
      description: "Ramas principales que organizan el catalogo de la empresa.",
      path: "/catalogo/familias/",
      statusField: "activa",
      order: "orden",
      columns: [
        { key: "imagen_final", label: "Imagen", type: "image" },
        { key: "nombre", label: "Familia", type: "primary", secondaryKey: "descripcion" },
        { key: "orden", label: "Orden", type: "number" },
        { key: "activa", label: "Estado", type: "status" },
      ],
      fields: [
        { name: "nombre", label: "Nombre", required: true },
        { name: "orden", label: "Orden", type: "number", min: 1, required: true },
        { name: "descripcion", label: "Descripcion", type: "textarea", full: true },
        ...commonImageFields,
        { name: "activa", label: "Familia activa", type: "switch", full: true },
      ],
      initialValues: { orden: 1, activa: true },
    },
    categorias: {
      key: "categorias",
      title: "Categorias",
      singular: "categoria",
      description: "Divisiones internas de cada familia de productos o servicios.",
      path: "/catalogo/categorias/",
      statusField: "activa",
      order: "orden",
      dependencies: ["familias"],
      columns: [
        { key: "imagen_final", label: "Imagen", type: "image" },
        { key: "nombre", label: "Categoria", type: "primary", secondaryKey: "descripcion" },
        { key: "familia_nombre", label: "Familia" },
        { key: "orden", label: "Orden", type: "number" },
        { key: "activa", label: "Estado", type: "status" },
      ],
      fields: [
        { name: "familia", label: "Familia", type: "select", source: "familias", required: true },
        { name: "nombre", label: "Nombre", required: true },
        { name: "orden", label: "Orden", type: "number", min: 1, required: true },
        { name: "descripcion", label: "Descripcion", type: "textarea", full: true },
        ...commonImageFields,
        { name: "activa", label: "Categoria activa", type: "switch", full: true },
      ],
      initialValues: { orden: 1, activa: true },
    },
    productos: {
      key: "productos",
      title: "Productos y servicios",
      singular: "articulo",
      description: "Precios, clasificacion y disponibilidad del catalogo vendible.",
      path: "/catalogo/productos/",
      statusField: "activo",
      order: "nombre",
      dependencies: ["familias", "categorias"],
      columns: [
        ...(company.productos_con_imagen
          ? [{ key: "imagen_final", label: "Imagen", type: "image" }]
          : []),
        { key: "nombre", label: "Articulo", type: "primary", secondaryKey: "codigo" },
        { key: "familia_nombre", label: "Familia" },
        { key: "categoria_nombre", label: "Categoria" },
        { key: "precio", label: "Precio", type: "currency" },
        ...(company.permite_productos_fisicos
          ? [{ key: "existencia", label: "Existencia", type: "number" }]
          : []),
        { key: "activo", label: "Estado", type: "status" },
      ],
      fields: [
        { name: "familia", label: "Familia", type: "select", source: "familias", required: true },
        {
          name: "categoria",
          label: "Categoria",
          type: "select",
          source: "categorias",
          filterBy: { field: "familia", draftField: "familia" },
          required: true,
        },
        {
          name: "tipo_item",
          label: "Tipo de articulo",
          type: "select",
          options: productTypeOptions,
          required: company.modo_inventario === "mixto",
          hidden: company.modo_inventario !== "mixto",
        },
        { name: "nombre", label: "Nombre", required: true, full: true },
        { name: "descripcion", label: "Descripcion", type: "textarea", full: true },
        { name: "codigo_barra", label: "Codigo de barras" },
        { name: "precio", label: "Precio", type: "number", min: 0, step: "0.01", required: true },
        ...(company.permite_productos_fisicos
          ? [{ name: "existencia_minima", label: "Existencia minima", type: "number", min: 0 }]
          : []),
        { name: "orden", label: "Orden destacado", type: "number", min: 0 },
        ...(company.productos_con_imagen
          ? [
              { name: "imagen_url", label: "URL externa de imagen", type: "url", full: true },
              { name: "imagen_principal", label: "Archivo de imagen", type: "file", accept: "image/*", full: true },
            ]
          : []),
        { name: "activo", label: "Articulo activo", type: "switch", full: true },
      ],
      initialValues: {
        activo: true,
        orden: 0,
        existencia_minima: 0,
        tipo_item:
          company.modo_inventario === "inventariado" ? "producto_fisico" : "servicio",
      },
    },
    paquetes: {
      key: "paquetes",
      title: "Perfiles y combos",
      singular: "paquete",
      description: "Agrupaciones vendibles con precio propio y composicion controlada.",
      path: "/catalogo/paquetes/",
      statusField: "activo",
      order: "orden",
      dependencies: ["productos"],
      columns: [
        { key: "imagen_final", label: "Imagen", type: "image" },
        { key: "nombre", label: "Paquete", type: "primary", secondaryKey: "codigo" },
        { key: "tipo_nombre", label: "Tipo" },
        { key: "precio", label: "Precio", type: "currency" },
        { key: "productos_detalle", label: "Componentes", type: "count" },
        { key: "activo", label: "Estado", type: "status" },
      ],
      fields: [
        { name: "tipo", label: "Tipo", type: "select", options: packageTypeOptions, required: true },
        { name: "codigo", label: "Codigo", required: true },
        { name: "nombre", label: "Nombre", required: true, full: true },
        { name: "descripcion", label: "Descripcion", type: "textarea", full: true },
        { name: "precio_normal", label: "Precio normal", type: "number", min: 0, step: "0.01", required: true },
        { name: "precio", label: "Precio de venta", type: "number", min: 0, step: "0.01", required: true },
        { name: "porcentaje_descuento", label: "Descuento (%)", type: "number", min: 0, max: 100 },
        { name: "orden", label: "Orden", type: "number", min: 1 },
        { name: "productos", label: "Productos incluidos", type: "productBuilder", source: "productos", full: true, required: true },
        ...commonImageFields,
        { name: "destacado", label: "Mostrar como destacado", type: "switch" },
        { name: "activo", label: "Paquete activo", type: "switch" },
      ],
      initialValues: { tipo: "perfil", orden: 1, destacado: false, activo: true, productos: [] },
    },
    menu: {
      key: "menu",
      title: "Menu de la tienda",
      singular: "opcion",
      description: "Personaliza el texto, orden y visibilidad de los modulos oficiales.",
      path: "/empresas/items-menu/",
      statusField: "activo",
      order: "orden",
      canCreate: false,
      canDelete: false,
      columns: [
        { key: "texto", label: "Opcion", type: "primary", secondaryKey: "clave" },
        { key: "ruta", label: "Destino", type: "code" },
        { key: "orden", label: "Orden", type: "number" },
        { key: "activo", label: "Estado", type: "status" },
      ],
      fields: [
        { name: "texto", label: "Texto visible", required: true },
        { name: "orden", label: "Orden", type: "number", min: 1, required: true },
        { name: "activo", label: "Opcion activa", type: "switch" },
      ],
      initialValues: { orden: 1, activo: true },
    },
    ciudades: {
      key: "ciudades",
      title: "Ciudades",
      singular: "ciudad",
      description: isSuperuser
        ? "Catalogo nacional de municipios disponibles para las sucursales."
        : "Catalogo nacional de municipios. Solo un superusuario puede modificarlo.",
      path: "/ubicaciones/municipios/",
      statusField: "activo",
      order: "nombre",
      dependencies: ["departamentos"],
      readOnly: !isSuperuser,
      ...(!isSuperuser
        ? { detailFields: ["codigo", "nombre", "departamento", "orden", "activo"] }
        : {}),
      columns: [
        { key: "nombre", label: "Ciudad", type: "primary", secondaryKey: "codigo" },
        { key: "departamento", label: "Departamento" },
        { key: "orden", label: "Orden", type: "number" },
        { key: "activo", label: "Estado", type: "status" },
      ],
      fields: [
        { name: "codigo", label: "Codigo", inputMode: "numeric", maxLength: 4, pattern: "[0-9]{4}", required: true },
        { name: "nombre", label: "Nombre", required: true, trim: true },
        { name: "departamento_id", label: "Departamento", type: "select", source: "departamentos", required: true },
        { name: "orden", label: "Orden", type: "number", min: 1, required: true },
        { name: "activo", label: "Ciudad activa", type: "switch", full: true },
      ],
      initialValues: { activo: true },
    },
    sucursales: {
      key: "sucursales",
      title: "Sucursales",
      singular: "sucursal",
      description: "Puntos de atencion, horarios y ubicaciones publicadas.",
      path: "/empresas/sucursales/",
      statusField: "estado",
      statusToggle: false,
      order: "orden",
      dependencies: ["municipios"],
      columns: [
        { key: "imagen_final", label: "Imagen", type: "image" },
        { key: "nombre", label: "Sucursal", type: "primary", secondaryKey: "direccion" },
        { key: "ciudad", label: "Ciudad" },
        { key: "departamento", label: "Departamento" },
        { key: "telefono", label: "Telefono" },
        { key: "horario", label: "Horario" },
        { key: "estado", label: "Estado", type: "branchStatus" },
      ],
      fields: [
        { name: "nombre", label: "Nombre", required: true },
        {
          name: "municipio_id",
          label: "Ciudad",
          type: "select",
          source: "municipios",
          optionLabel: (option) => `${option.nombre} - ${option.departamento}`,
          required: true,
        },
        { name: "telefono", label: "Telefono", ...phoneFieldProps },
        { name: "direccion", label: "Direccion", type: "textarea", full: true },
        { name: "horario", label: "Horario", full: true },
        { name: "google_maps_url", label: "Enlace de Google Maps", type: "url", full: true },
        { name: "latitud", label: "Latitud", type: "number", step: "any" },
        { name: "longitud", label: "Longitud", type: "number", step: "any" },
        { name: "orden", label: "Orden", type: "number", min: 1 },
        ...commonImageFields,
        { name: "estado", label: "Estado", type: "select", options: branchStatusOptions, required: true },
      ],
      initialValues: { orden: 1, estado: "activa" },
    },
    banners: {
      key: "banners",
      title: "Banners",
      singular: "banner",
      description: "Imagenes clicables que aparecen en el carrusel de Inicio.",
      path: "/promociones/banners/",
      statusField: "activo",
      order: "orden",
      columns: [
        { key: "imagen_final", label: "Vista", type: "wideImage" },
        { key: "titulo", label: "Banner", type: "primary", secondaryKey: "texto_alternativo" },
        { key: "url_boton", label: "Destino", type: "code" },
        { key: "orden", label: "Orden", type: "number" },
        { key: "esta_vigente", label: "Vigencia", type: "status" },
        { key: "activo", label: "Estado", type: "status" },
      ],
      fields: [
        { name: "titulo", label: "Titulo", required: true },
        { name: "subtitulo", label: "Subtitulo" },
        { name: "texto_alternativo", label: "Texto alternativo", full: true, required: true },
        { name: "url_boton", label: "Destino al hacer clic", full: true },
        { name: "texto_boton", label: "Texto interno del boton" },
        { name: "orden", label: "Orden", type: "number", min: 1 },
        { name: "fecha_inicio", label: "Inicio", type: "datetime-local" },
        { name: "fecha_fin", label: "Fin", type: "datetime-local" },
        ...commonImageFields,
        { name: "activo", label: "Banner activo", type: "switch", full: true },
      ],
      initialValues: { orden: 1, activo: true },
    },
    ofertas: {
      key: "ofertas",
      title: "Ofertas",
      singular: "oferta",
      description: "Promociones visuales publicadas en la pagina de ofertas.",
      path: "/promociones/ofertas/",
      statusField: "activo",
      order: "orden",
      dependencies: ["productos", "paquetes"],
      columns: [
        { key: "imagen_final", label: "Imagen", type: "image" },
        { key: "titulo", label: "Oferta", type: "primary", secondaryKey: "codigo" },
        { key: "tipo_nombre", label: "Tipo" },
        { key: "precio_oferta", label: "Precio", type: "currency" },
        { key: "porcentaje_descuento", label: "Descuento", type: "percent" },
        { key: "activo", label: "Estado", type: "status" },
      ],
      fields: [
        { name: "tipo", label: "Tipo", type: "select", options: [
          { value: "producto", label: "Un producto" },
          { value: "productos", label: "Varios productos" },
          { value: "paquete", label: "Perfil o combo" },
        ], required: true },
        { name: "codigo", label: "Codigo", required: true },
        { name: "titulo", label: "Titulo", required: true, full: true },
        { name: "descripcion", label: "Descripcion", type: "textarea", full: true },
        { name: "precio_normal", label: "Precio normal", type: "number", min: 0, step: "0.01", required: true },
        { name: "precio_oferta", label: "Precio de oferta", type: "number", min: 0, step: "0.01", required: true },
        { name: "porcentaje_descuento", label: "Descuento (%)", type: "number", min: 0, max: 100 },
        { name: "productos_ids", label: "Productos", type: "multiSelect", source: "productos", full: true, visible: (draft) => draft.tipo !== "paquete" },
        { name: "paquete", label: "Perfil o combo", type: "select", source: "paquetes", full: true, visible: (draft) => draft.tipo === "paquete" },
        { name: "url_destino", label: "Ruta de destino", full: true },
        { name: "orden", label: "Orden", type: "number", min: 1 },
        { name: "fecha_inicio", label: "Inicio", type: "datetime-local" },
        { name: "fecha_fin", label: "Fin", type: "datetime-local" },
        ...commonImageFields,
        { name: "activo", label: "Oferta activa", type: "switch", full: true },
      ],
      initialValues: { tipo: "producto", orden: 1, activo: true, productos_ids: [] },
    },
    descuentos: {
      key: "descuentos",
      title: "Descuentos del carrito",
      singular: "descuento",
      description: "Reglas porcentuales aplicadas por el servidor al confirmar precios.",
      path: "/promociones/descuentos/",
      statusField: "activo",
      order: "-porcentaje",
      dependencies: ["productos"],
      columns: [
        { key: "titulo", label: "Regla", type: "primary", secondaryKey: "codigo" },
        { key: "alcance_nombre", label: "Alcance" },
        { key: "porcentaje", label: "Descuento", type: "percent" },
        { key: "productos", label: "Articulos", type: "count" },
        { key: "esta_vigente", label: "Vigencia", type: "status" },
        { key: "activo", label: "Estado", type: "status" },
      ],
      fields: [
        { name: "codigo", label: "Codigo", required: true },
        { name: "titulo", label: "Titulo", required: true },
        { name: "descripcion", label: "Descripcion", type: "textarea", full: true },
        { name: "alcance", label: "Alcance", type: "select", options: [
          { value: "todos", label: "Todos los articulos" },
          { value: "seleccionados", label: "Articulos seleccionados" },
          { value: "individual", label: "Un articulo" },
        ], required: true },
        { name: "porcentaje", label: "Porcentaje", type: "number", min: 1, max: 99, required: true },
        { name: "productos_ids", label: "Productos", type: "multiSelect", source: "productos", full: true, visible: (draft) => draft.alcance !== "todos" },
        { name: "fecha_inicio", label: "Inicio", type: "datetime-local" },
        { name: "fecha_fin", label: "Fin", type: "datetime-local" },
        { name: "activo", label: "Regla activa", type: "switch", full: true },
      ],
      initialValues: { alcance: "todos", porcentaje: 10, activo: true, productos_ids: [] },
    },
    usuarios: {
      key: "usuarios",
      title: "Usuarios",
      singular: "usuario",
      description: "Accesos, roles y estado de las cuentas vinculadas a la empresa.",
      path: "/usuarios/administracion/",
      statusField: "activo",
      statusActions: { activate: "desbloquear", deactivate: "bloquear" },
      canCreate:
        isSuperuser ||
        actorRole === "administrador_maestro" ||
        context?.perfil?.puede_crear_usuarios === true,
      canDelete: false,
      order: "first_name",
      columns: [
        { key: "first_name", label: "Usuario", type: "person", secondaryKey: "email" },
        { key: "rol_nombre", label: "Rol" },
        { key: "telefono", label: "Telefono" },
        { key: "correo_verificado", label: "Correo", type: "verified" },
        { key: "activo", label: "Estado", type: "status" },
      ],
      fields: [
        { name: "username", label: "Nombre de usuario", required: true },
        { name: "email", label: "Correo", type: "email", required: true },
        { name: "first_name", label: "Nombre" },
        { name: "last_name", label: "Apellido" },
        { name: "password", label: "Contraseña", type: "password", full: true, createRequired: true, placeholder: "Solo se cambia si escribes una nueva" },
        { name: "rol", label: "Rol", type: "select", options: availableUserRoles, required: true },
        { name: "telefono", label: "Telefono", ...phoneFieldProps },
        { name: "numero_identidad", label: "Identidad", placeholder: "13 digitos" },
        ...(isSuperuser
          ? [
              { name: "empresa", label: "Empresa", type: "companySelect", full: true, visible: (draft) => draft.rol !== "administrador_maestro" },
              { name: "empresas_permitidas", label: "Empresas permitidas", type: "companyMultiSelect", full: true, visible: (draft) => draft.rol === "administrador_maestro" },
            ]
          : []),
        { name: "correo_verificado", label: "Correo verificado", type: "switch" },
        { name: "puede_crear_usuarios", label: "Puede crear usuarios", type: "switch" },
        { name: "activo", label: "Cuenta activa", type: "switch" },
      ],
      initialValues: { rol: "comprador", correo_verificado: true, puede_crear_usuarios: false, activo: true },
    },
    contactos: {
      key: "contactos",
      title: "Mensajes",
      singular: "mensaje",
      description: "Consultas y sugerencias enviadas desde la tienda.",
      path: "/contacto/mensajes/",
      canCreate: false,
      canDelete: false,
      statusField: "estado",
      order: "-fecha_creacion",
      columns: [
        { key: "nombre", label: "Remitente", type: "primary", secondaryKey: "correo" },
        { key: "asunto", label: "Asunto" },
        { key: "mensaje", label: "Mensaje", type: "truncate" },
        { key: "fecha_creacion", label: "Recibido", type: "date" },
        { key: "estado", label: "Estado", type: "contactStatus" },
      ],
      fields: [
        { name: "estado", label: "Estado", type: "select", options: [
          { value: "nuevo", label: "Nuevo" },
          { value: "pendiente", label: "Pendiente" },
          { value: "respondido", label: "Respondido" },
        ], required: true, full: true },
      ],
      detailFields: ["nombre", "telefono", "correo", "asunto", "mensaje", "fecha_creacion"],
    },
    pedidos: {
      key: "pedidos",
      title: "Pedidos",
      singular: "pedido",
      description: "Historial comercial congelado al confirmar cada compra.",
      path: "/pedidos/pedidos/",
      readOnly: true,
      order: "-fecha_creacion",
      statusFilter: {
        label: "Estado del pedido",
        param: "estado_pago",
        options: [
          { value: "", label: "Todos" },
          { value: "pendiente", label: "Pendientes" },
          { value: "pagado", label: "Pagados" },
          { value: "cancelado", label: "Cancelados" },
        ],
      },
      columns: [
        { key: "numero", label: "Pedido", type: "primary", secondaryKey: "usuario_nombre" },
        { key: "tipo_entrega", label: "Entrega" },
        { key: "total", label: "Total", type: "currency" },
        { key: "detalles", label: "Articulos", type: "count" },
        { key: "fecha_creacion", label: "Fecha", type: "date" },
        { key: "metodo_pago", label: "Metodo", type: "paymentMethod" },
        { key: "estado_pago", label: "Pago", type: "paymentStatus" },
      ],
      detailFields: ["numero", "usuario_nombre", "tipo_entrega", "metodo_pago", "estado_pago", "subtotal", "descuento_total", "impuesto", "envio", "total", "observaciones", "motivo_cancelacion", "cancelado_por_email", "fecha_cancelacion", "fecha_creacion"],
    },
    pagos: {
      key: "pagos",
      title: "Pagos",
      singular: "pago",
      description: "Intentos de pago y confirmaciones recibidas del proveedor.",
      path: "/pagos/",
      readOnly: true,
      order: "-fecha_creacion",
      rowId: "referencia",
      statusFilter: {
        label: "Estado del pago",
        param: "estado",
        options: [
          { value: "", label: "Todos" },
          { value: "pendiente", label: "Pendientes" },
          { value: "aprobado", label: "Aprobados" },
          { value: "rechazado", label: "Rechazados" },
          { value: "cancelado", label: "Cancelados" },
        ],
      },
      columns: [
        { key: "referencia", label: "Referencia", type: "code" },
        { key: "pedido_numero", label: "Pedido", type: "primary", secondaryKey: "usuario_email" },
        { key: "metodo", label: "Metodo", type: "paymentMethod" },
        { key: "proveedor", label: "Proveedor" },
        { key: "monto", label: "Monto", type: "currency" },
        { key: "fecha_creacion", label: "Fecha", type: "date" },
        { key: "estado", label: "Estado", type: "paymentStatus" },
      ],
      detailFields: ["referencia", "pedido_numero", "usuario_email", "metodo", "proveedor", "identificador_externo", "monto", "moneda", "estado", "estado_nombre", "codigo_respuesta", "fecha_confirmacion", "fecha_creacion"],
    },
    empresas: {
      key: "empresas",
      title: "Empresas",
      singular: "empresa",
      description: "Tenants, dominios y configuracion comercial general.",
      path: "/empresas/",
      statusField: "activa",
      canAccess: isSuperuser,
      columns: [
        { key: "logo", label: "Logo", type: "image" },
        { key: "nombre", label: "Empresa", type: "primary", secondaryKey: "slug" },
        { key: "dominio_personalizado", label: "Dominio" },
        { key: "modo_inventario_nombre", label: "Operacion" },
        { key: "activa", label: "Estado", type: "status" },
      ],
      fields: [
        { name: "nombre", label: "Nombre", required: true },
        { name: "slug", label: "Slug" },
        { name: "subdominio", label: "Subdominio" },
        { name: "dominio_personalizado", label: "Dominio personalizado", full: true },
        { name: "telefono", label: "Telefono", ...phoneFieldProps },
        { name: "correo", label: "Correo", type: "email" },
        { name: "direccion", label: "Direccion", type: "textarea", full: true },
        { name: "sitio_web", label: "Sitio web", type: "url", full: true },
        { name: "modo_inventario", label: "Modo de inventario", type: "select", options: [
          { value: "inventariado", label: "Con inventario" },
          { value: "sin_inventario", label: "Solo servicios" },
          { value: "mixto", label: "Mixto" },
        ], required: true },
        { name: "logo", label: "Logo", type: "file", accept: "image/*", full: true },
        { name: "tiene_envios", label: "Tiene envios", type: "switch" },
        { name: "cobra_impuesto", label: "Cobra impuesto", type: "switch" },
        { name: "productos_con_imagen", label: "Productos con imagen", type: "switch" },
        { name: "activa", label: "Empresa activa", type: "switch" },
      ],
      initialValues: { modo_inventario: "sin_inventario", tiene_envios: false, cobra_impuesto: false, productos_con_imagen: true, activa: true },
    },
  };
}
